BULK-Updates-2024-06-06
smnorris/bcfishpass pull request #509
Opened 2024-06-06 18:46 UTC by LauraB-CWF

Removal of trailing commas and structure 360777770.

2024-06-07 20:09 UTC, smnorris requested changes
Should be fine once the duplicate row is removed.

2024-06-07 20:09 UTC, smnorris commented on data/user_habitat_classification.csv
> +360879788,0,100,NASC,SK,spawning,t,SN,2023-09-01,Pacific Salmon Foundation,manually matched360879788,0,100,NASC,SK,spawning,t,SN,2023-09-01,Pacific Salmon Foundation,manually matched
This row is duplicated / missing a line break

2024-06-07 20:12 UTC, smnorris commented
One other question - PSF is noted as source for this new CO/SK observed spawning.
Is there any background on this? Just wondering if this is new data or if it something that was missed on previous data loads.

2024-06-10 12:52 UTC, LauraB-CWF commented
Hi Simon,

This is data that was missed. I have images of all the locations too if you want to review.

Thank you,

Laura Bernardi
GIS Technician
***@***.***
350, promenade Michael Cowpland Drive, Kanata, ON K2M 2W1
1.877.599.5777 | 613.599.9594
CanadianWildlifeFederation.ca<http://www.canadianwildlifefederation.ca/?src=signature> | Federationcanadiennedelafaune.ca<http://www.federationcanadiennedelafaune.ca/?src=signature>

[seeds]<http://donate.cwf-fcf.org/site/Donation2?df_id=7440&mfc_pref=T&7440.donation=form1&utm_source=signature&utm_medium=referral&utm_campaign=biod>

Let's celebrate Canada's biodiversity by planting pollinator-friendly seeds.
Request your free seeds ><http://donate.cwf-fcf.org/site/Donation2?df_id=7440&mfc_pref=T&7440.donation=form1?utm_source=signature&utm_medium=email&utm_campaign=mmg>
---------------------------------------
Célébrons la biodiversité du Canada en plantant des semences favorables aux pollinisateurs.
Demandez vos semences gratuites ><http://donate.cwf-fcf.org/site/Donation2?df_id=7440&mfc_pref=T&7440.donation=form1?utm_source=signature&utm_medium=referral&utm_campaign=biod&s_locale=fr_CA>

From: Simon Norris ***@***.***>
Sent: Friday, June 7, 2024 4:13 PM
To: smnorris/bcfishpass ***@***.***>
Cc: Laura Bernardi ***@***.***>; Author ***@***.***>
Subject: Re: [smnorris/bcfishpass] BULK-Updates-2024-06-06 (PR #509)


CAUTION: EXTERNAL EMAIL / ATTENTION: COURRIEL EXTERNE

One other question - PSF is noted as source for this new CO/SK observed spawning.
Is there any background on this? Just wondering if this is new data or if it something that was missed on previous data loads.

-
Reply to this email directly, view it on GitHub<https://github.com/smnorris/bcfishpass/pull/509#issuecomment-2155483447>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BCMSYWFCOJK7546SJH6HOITZGIH3XAVCNFSM6AAAAABI5JFD4KVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCNJVGQ4DGNBUG4>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

2024-06-10 17:24 UTC, smnorris commented
No need, thanks Laura

2024-06-11 22:51 UTC, smnorris commented
A couple of changes that would be great for future fixes:

1. Measure precision
There is no need to record measures to 5 decimal places - rounding to the nearest metre is fine (and preferred)

2. More descriptive notes per PR and per row would be great
Per PR is as per my question above, just some context
Per row mostly is fine to date - but for example I can't tell what things like `Upstream - 110.991 m` refers to in notes

2024-06-11 22:52 UTC, merged

2024-06-12 11:46 UTC, LauraB-CWF commented
Hi Simon,

I appreciate this feedback and will keep this in find for all updates I make.

Thank you,

Laura Bernardi
GIS Technician
***@***.***
350, promenade Michael Cowpland Drive, Kanata, ON K2M 2W1
1.877.599.5777 | 613.599.9594
CanadianWildlifeFederation.ca<http://www.canadianwildlifefederation.ca/?src=signature> | Federationcanadiennedelafaune.ca<http://www.federationcanadiennedelafaune.ca/?src=signature>

[seeds]<http://donate.cwf-fcf.org/site/Donation2?df_id=7440&mfc_pref=T&7440.donation=form1&utm_source=signature&utm_medium=referral&utm_campaign=biod>

Let's celebrate Canada's biodiversity by planting pollinator-friendly seeds.
Request your free seeds ><http://donate.cwf-fcf.org/site/Donation2?df_id=7440&mfc_pref=T&7440.donation=form1?utm_source=signature&utm_medium=email&utm_campaign=mmg>
---------------------------------------
Célébrons la biodiversité du Canada en plantant des semences favorables aux pollinisateurs.
Demandez vos semences gratuites ><http://donate.cwf-fcf.org/site/Donation2?df_id=7440&mfc_pref=T&7440.donation=form1?utm_source=signature&utm_medium=referral&utm_campaign=biod&s_locale=fr_CA>

From: Simon Norris ***@***.***>
Sent: Tuesday, June 11, 2024 6:52 PM
To: smnorris/bcfishpass ***@***.***>
Cc: Laura Bernardi ***@***.***>; Author ***@***.***>
Subject: Re: [smnorris/bcfishpass] BULK-Updates-2024-06-06 (PR #509)


CAUTION: EXTERNAL EMAIL / ATTENTION: COURRIEL EXTERNE

A couple of changes that would be great for future fixes:

  1.  Measure precision
There is no need to record measures to 5 decimal places - rounding to the nearest metre is fine (and preferred)
  2.  More descriptive notes per PR and per row would be great
Per PR is as per my question above, just some context
Per row mostly is fine to date - but for example I can't tell what things like Upstream - 110.991 m refers to in notes

-
Reply to this email directly, view it on GitHub<https://github.com/smnorris/bcfishpass/pull/509#issuecomment-2161728445>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BCMSYWA6K2HAK4CQW7PNBD3ZG55RZAVCNFSM6AAAAABI5JFD4KVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCNRRG4ZDQNBUGU>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>