BOWR/QUES assessment data updates
smnorris/bcfishpass pull request #533
Opened 2024-07-04 20:12 UTC by matthewcooper11

BOWR/QUES data updates. I also tried syncing my fork with the main bcfishpass as per Simon's previous comments on changes I have pushed.

2024-07-04 22:21 UTC, smnorris commented
Not sure why the test build fails, I've opened a separate issue and will look in to that.
There are a bunch of issues with the PR that are just related to file syncing. It might be easiest for me to work through them but I'll point them out.

2024-07-04 22:46 UTC, smnorris requested changes
For the technical issues I've noted, it might be easiest to create a fresh clone or fork rather than working through the merge conflicts and file permissions/line endings.

I also have questions about some of the adjustments, I'll direct those to the group.

2024-07-04 22:46 UTC, smnorris commented on jobs/bcfishpass01_modelled_stream_crossings
All these scripts need to be executable (755), but have somehow been modified to 644. 
I think you need to update your git config to prevent this from happening https://stackoverflow.com/questions/1257592/how-do-i-remove-files-saying-old-mode-100755-new-mode-100644-from-unstaged-cha

2024-07-04 22:46 UTC, smnorris commented on parameters/example_newgraph/parameters_habitat_method.csv
Looks like it is probably just the line endings that have changed in this file? Not a file I'd expect to see changed.

2024-07-04 22:46 UTC, smnorris commented on data/user_pscis_barrier_status.csv
> +<<<<<<< HEAD
If you've merged the latest and there are conflicts, you need to resolve the conflicts and take out the various pointers like this:
```
<<<<<<< HEAD
=======
```
and
```
>>>>>>> 5b39c1fa9a4efc2704ae7469b1fadad137846468
```

With our current workflow these conflicts are going to pop up now and then when several users make changes to the same file.

2024-07-04 22:54 UTC, smnorris reviewed
What is the source for "Field Assessments"? 
Are these taken from PSCIS? And if from PSCIS, why is there info for the crossing but no assessment? 
Or is this some other field source? 
Where there is a source available, we should provide a link and/or citation.

2024-07-05 19:56 UTC, nickw-CWF commented
> What is the source for "Field Assessments"? Are these taken from PSCIS? And if from PSCIS, why is there info for the crossing but no assessment? Or is this some other field source? Where there is a source available, we should provide a link and/or citation.

These are from field assessments that a partner did, but there was no crossing or stream at the site so there was no PSCIS submission. We don't have a formal report to cite, but we could add the group that did the assessments (in this case Lhtako Dene). Would that work?

> Not sure why the test build fails, I've opened a separate issue and will look in to that. There are a bunch of issues with the PR that are just related to file syncing. It might be easiest for me to work through them but I'll point them out.

Just to make sure we're on the same page, will you resolve the technical issues for this PR or do you want @matthewcooper11 do create a fresh clone and try to submit again (he can add detail to the source field as well)?

2024-07-05 20:06 UTC, smnorris commented
> > What is the source for "Field Assessments"? Are these taken from PSCIS? And if from PSCIS, why is there info for the crossing but no assessment? Or is this some other field source? Where there is a source available, we should provide a link and/or citation.
> 
> These are from field assessments that a partner did, but there was no crossing or stream at the site so there was no PSCIS submission. We don't have a formal report to cite, but we could add the group that did the assessments (in this case Lhtako Dene). Would that work?
> 
That would be perfect.

> > Not sure why the test build fails, I've opened a separate issue and will look in to that. There are a bunch of issues with the PR that are just related to file syncing. It might be easiest for me to work through them but I'll point them out.
> 
> Just to make sure we're on the same page, will you resolve the technical issues for this PR or do you want @matthewcooper11 do create a fresh clone and try to submit again (he can add detail to the source field as well)?

Either is fine but if @matthewcooper11 can add the details and create a fresh PR that is easiest.

2024-07-08 19:57 UTC, closed without merging